services:
  coreai-mcu-document-processor:
    build:
      context: .
      target: production
    image: coreai-mcu-document-processor
    container_name: coreai-mcu-document-processor
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-document-processor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://coreai-mcu-document-processor-azurite:10000/devstoreaccount1;;TableEndpoint=http://coreai-mcu-document-processor-azurite:10002/devstoreaccount1;
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}
      POLLING_INTERVAL: ${POLLING_INTERVAL:-10000}
      MAX_PROCESSING_TRIES: ${MAX_PROCESSING_TRIES:-3}

  coreai-mcu-document-processor-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
