services:
  coreai-mcu-document-processor:
    build:
      context: .
      target: production
    image: coreai-mcu-document-processor
    container_name: coreai-mcu-document-processor
    depends_on:
      - coreai-mcu-document-processor-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-document-processor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-document-processor-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-document-processor
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
